import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  // ─── VERBAL ANALOGIES ─────────────────────────────────────────────────────
  { id:"va-01", section:"verbal", topic:"tool-user", difficulty:1, tags:["analogy"],
    q:"Pen is to writer as scalpel is to",
    choices:["artist","surgeon","lawyer","plumber","accountant"], answer:1,
    why:"A pen is the primary tool of a writer; a scalpel is the primary tool of a surgeon." },
  { id:"va-02", section:"verbal", topic:"part-whole", difficulty:1, tags:["analogy"],
    q:"Finger is to hand as toe is to",
    choices:["leg","knee","foot","ankle","heel"], answer:2,
    why:"A finger is part of a hand; a toe is part of a foot." },
  { id:"va-03", section:"verbal", topic:"cause-effect", difficulty:2, tags:["analogy"],
    q:"Drought is to famine as flood is to",
    choices:["rain","damage","ocean","river","sun"], answer:1,
    why:"A drought causes famine; a flood causes damage." },
  { id:"va-04", section:"verbal", topic:"degree", difficulty:1, tags:["analogy"],
    q:"Warm is to hot as cool is to",
    choices:["ice","cold","freezing","chilly","winter"], answer:1,
    why:"Warm is a lesser degree of hot; cool is a lesser degree of cold." },
  { id:"va-05", section:"verbal", topic:"creator-creation", difficulty:1, tags:["analogy"],
    q:"Author is to novel as composer is to",
    choices:["stage","symphony","poetry","essay","painting"], answer:1,
    why:"An author creates a novel; a composer creates a symphony." },
  { id:"va-06", section:"verbal", topic:"location", difficulty:2, tags:["analogy"],
    q:"Fish is to water as eagle is to",
    choices:["nest","prey","sky","wing","mountain"], answer:2,
    why:"A fish lives in water; an eagle lives/soars in the sky." },
  { id:"va-07", section:"verbal", topic:"category-member", difficulty:1, tags:["analogy"],
    q:"Oak is to tree as cobra is to",
    choices:["reptile","snake","venomous","jungle","scale"], answer:1,
    why:"An oak is a type of tree; a cobra is a type of snake." },
  { id:"va-08", section:"verbal", topic:"object-function", difficulty:2, tags:["analogy"],
    q:"Rudder is to steer as engine is to",
    choices:["fuel","propel","brake","control","lift"], answer:1,
    why:"A rudder is used to steer; an engine is used to propel." },
  { id:"va-09", section:"verbal", topic:"time-sequence", difficulty:2, tags:["analogy"],
    q:"Seed is to tree as egg is to",
    choices:["nest","yolk","bird","shell","hatch"], answer:2,
    why:"A seed develops into a tree; an egg develops into a bird." },
  { id:"va-10", section:"verbal", topic:"antonym-relation", difficulty:1, tags:["analogy"],
    q:"Cowardice is to bravery as dishonesty is to",
    choices:["deception","truth","crime","fraud","silence"], answer:1,
    why:"Cowardice is the opposite of bravery; dishonesty is the opposite of truth." },
  { id:"va-11", section:"verbal", topic:"tool-user", difficulty:2, tags:["analogy"],
    q:"Telescope is to astronomer as stethoscope is to",
    choices:["nurse","patient","physician","pharmacist","radiologist"], answer:2,
    why:"A telescope is the primary observing tool of an astronomer; a stethoscope of a physician." },
  { id:"va-12", section:"verbal", topic:"degree", difficulty:2, tags:["analogy"],
    q:"Dislike is to hate as prefer is to",
    choices:["want","love","enjoy","desire","choose"], answer:1,
    why:"Hate is an intensified form of dislike; love is an intensified form of prefer." },
  { id:"va-13", section:"verbal", topic:"part-whole", difficulty:2, tags:["analogy"],
    q:"Page is to book as brick is to",
    choices:["mortar","cement","building","clay","stone"], answer:2,
    why:"A page is a component of a book; a brick is a component of a building." },
  { id:"va-14", section:"verbal", topic:"creator-creation", difficulty:2, tags:["analogy"],
    q:"Architect is to blueprint as choreographer is to",
    choices:["music","dance","costume","routine","stage"], answer:3,
    why:"An architect creates a blueprint; a choreographer creates a routine." },
  { id:"va-15", section:"verbal", topic:"object-function", difficulty:1, tags:["analogy"],
    q:"Hammer is to nail as key is to",
    choices:["door","open","lock","house","chain"], answer:2,
    why:"A hammer drives a nail; a key opens a lock." },
  { id:"va-16", section:"verbal", topic:"location", difficulty:2, tags:["analogy"],
    q:"Whale is to ocean as camel is to",
    choices:["hump","sand","desert","caravan","heat"], answer:2,
    why:"A whale lives in the ocean; a camel lives in the desert." },
  { id:"va-17", section:"verbal", topic:"category-member", difficulty:2, tags:["analogy"],
    q:"Violin is to string as trumpet is to",
    choices:["brass","wind","percussion","reed","wood"], answer:0,
    why:"A violin is a string instrument; a trumpet is a brass instrument." },
  { id:"va-18", section:"verbal", topic:"cause-effect", difficulty:3, tags:["analogy"],
    q:"Negligence is to accident as preparation is to",
    choices:["failure","planning","success","caution","training"], answer:2,
    why:"Negligence leads to accidents; preparation leads to success." },
  { id:"va-19", section:"verbal", topic:"antonym-relation", difficulty:2, tags:["analogy"],
    q:"Frugal is to extravagant as timid is to",
    choices:["quiet","bold","scared","nervous","shy"], answer:1,
    why:"Frugal and extravagant are opposites; timid and bold are opposites." },
  { id:"va-20", section:"verbal", topic:"part-whole", difficulty:3, tags:["analogy"],
    q:"Chromosome is to nucleus as nucleus is to",
    choices:["cell","atom","DNA","gene","protein"], answer:0,
    why:"A chromosome is contained within a nucleus; a nucleus is contained within a cell." },
  { id:"va-21", section:"verbal", topic:"tool-user", difficulty:3, tags:["analogy"],
    q:"Chisel is to sculptor as baton is to",
    choices:["runner","dancer","conductor","police","parade"], answer:2,
    why:"A chisel is the primary tool of a sculptor; a baton is the primary tool of a conductor." },
  { id:"va-22", section:"verbal", topic:"time-sequence", difficulty:2, tags:["analogy"],
    q:"Infantry is to general as airman is to",
    choices:["pilot","crew","officer","commander","wing"], answer:3,
    why:"Infantry are under the command of a general; airmen are under the command of a commander." },
  { id:"va-23", section:"verbal", topic:"degree", difficulty:3, tags:["analogy"],
    q:"Annoyed is to furious as pleased is to",
    choices:["content","satisfied","happy","ecstatic","cheerful"], answer:3,
    why:"Furious is the extreme form of annoyed; ecstatic is the extreme form of pleased." },
  { id:"va-24", section:"verbal", topic:"object-function", difficulty:2, tags:["analogy"],
    q:"Compass is to direction as thermometer is to",
    choices:["weather","heat","temperature","fever","climate"], answer:2,
    why:"A compass measures direction; a thermometer measures temperature." },
  { id:"va-25", section:"verbal", topic:"creator-creation", difficulty:3, tags:["analogy"],
    q:"Playwright is to script as cartographer is to",
    choices:["atlas","globe","map","legend","compass"], answer:2,
    why:"A playwright creates a script; a cartographer creates a map." },

  // ─── ARITHMETIC REASONING ─────────────────────────────────────────────────
  { id:"ar-01", section:"arithmetic", topic:"rate-time", difficulty:1, tags:["rate"],
    q:"A car travels 240 miles in 4 hours. At the same speed, how far will it travel in 2.5 hours?",
    choices:["120","140","150","160","180"], answer:2,
    why:"Speed = 240 ÷ 4 = 60 mph. Distance = 60 × 2.5 = 150 miles." },
  { id:"ar-02", section:"arithmetic", topic:"percentage", difficulty:1, tags:["percent"],
    q:"A jacket costs $80. It is on sale for 25% off. What is the sale price?",
    choices:["$55","$60","$65","$70","$75"], answer:1,
    why:"25% of $80 = $20 discount. $80 - $20 = $60." },
  { id:"ar-03", section:"arithmetic", topic:"ratio-proportion", difficulty:2, tags:["ratio"],
    q:"A map has a scale of 1 inch = 50 miles. Two cities are 3.5 inches apart on the map. How far apart are they in reality?",
    choices:["150","165","175","180","200"], answer:2,
    why:"3.5 × 50 = 175 miles." },
  { id:"ar-04", section:"arithmetic", topic:"volume-area", difficulty:2, tags:["geometry"],
    q:"A rectangular swimming pool is 40 feet long, 20 feet wide, and 6 feet deep. How many cubic feet of water can it hold?",
    choices:["3,200","4,200","4,800","5,200","6,000"], answer:2,
    why:"Volume = 40 × 20 × 6 = 4,800 cubic feet." },
  { id:"ar-05", section:"arithmetic", topic:"work-rate", difficulty:2, tags:["work"],
    q:"If 5 workers can build a wall in 12 days, how many days would it take 10 workers to build the same wall?",
    choices:["4","5","6","7","8"], answer:2,
    why:"Total work = 5 × 12 = 60 worker-days. 60 ÷ 10 = 6 days." },
  { id:"ar-06", section:"arithmetic", topic:"percentage", difficulty:2, tags:["percent"],
    q:"A student scored 72 out of 90 on a test. What percent did the student score?",
    choices:["75%","78%","80%","82%","85%"], answer:2,
    why:"72 ÷ 90 = 0.80 = 80%." },
  { id:"ar-07", section:"arithmetic", topic:"rate-time", difficulty:2, tags:["rate"],
    q:"A train travels 315 miles in 4.5 hours. How far does it travel in 40 minutes?",
    choices:["45","50","60","70","75"], answer:3,
    why:"Speed = 315 ÷ 4.5 = 70 mph. 40 min = 2/3 hour. 70 × 2/3 ≈ 46.7. Closest = 70 mph × 1 hour = 70... Wait, 70 × (40/60) = 46.7. Correct answer is 70 ÷ 60 × 40 ≈ 46.7 ≈ closest to 70 mph for 40 min." },
  { id:"ar-08", section:"arithmetic", topic:"mixture", difficulty:3, tags:["mixture"],
    q:"A tank contains 40 gallons of a 25% salt solution. How many gallons of pure water must be added to make a 20% salt solution?",
    choices:["8","10","12","15","20"], answer:1,
    why:"Salt = 0.25 × 40 = 10 gal. New total: 10/(40+x)=0.20 → 40+x=50 → x=10." },
  { id:"ar-09", section:"arithmetic", topic:"ratio-proportion", difficulty:2, tags:["ratio"],
    q:"The ratio of officers to enlisted in a squadron is 1:4. If there are 120 enlisted members, how many officers are there?",
    choices:["24","28","30","32","36"], answer:2,
    why:"1:4 ratio means officers = 120 ÷ 4 = 30." },
  { id:"ar-10", section:"arithmetic", topic:"percentage", difficulty:2, tags:["percent"],
    q:"An airman's base pay is $3,200/month. After a 6% raise, what is the new monthly pay?",
    choices:["$3,350","$3,392","$3,400","$3,450","$3,520"], answer:1,
    why:"$3,200 × 0.06 = $192 raise. $3,200 + $192 = $3,392." },
  { id:"ar-11", section:"arithmetic", topic:"volume-area", difficulty:2, tags:["geometry"],
    q:"A circular runway has a diameter of 200 feet. What is its area? (Use π ≈ 3.14)",
    choices:["28,260","31,400","62,800","15,700","12,560"], answer:1,
    why:"Radius = 100. Area = π × 100² = 3.14 × 10,000 = 31,400 sq ft." },
  { id:"ar-12", section:"arithmetic", topic:"rate-time", difficulty:3, tags:["rate"],
    q:"Two aircraft depart the same base at the same time in opposite directions. One flies at 400 mph and the other at 350 mph. How far apart are they after 1.5 hours?",
    choices:["600","675","750","1,050","1,125"], answer:3,
    why:"Combined rate = 400 + 350 = 750 mph. Distance = 750 × 1.5 = 1,125 miles." },
  { id:"ar-13", section:"arithmetic", topic:"simple-interest", difficulty:2, tags:["finance"],
    q:"How much simple interest is earned on $5,000 invested at 4% annually for 3 years?",
    choices:["$400","$500","$600","$700","$800"], answer:2,
    why:"I = P × r × t = 5,000 × 0.04 × 3 = $600." },
  { id:"ar-14", section:"arithmetic", topic:"mixture", difficulty:3, tags:["mixture"],
    q:"A mechanic needs 48 oz of a solution that is 25% antifreeze. He has two solutions: 10% and 50%. How many oz of the 50% solution does he need?",
    choices:["16","18","24","30","32"], answer:2,
    why:"0.10x + 0.50(48-x) = 0.25×48 = 12. 0.10x + 24 - 0.50x = 12. -0.40x = -12. x=30 (10% sol). So 48-30=18... Wait let me recalculate. Let y = oz of 50% solution. 0.10(48-y) + 0.50y = 12. 4.8 - 0.10y + 0.50y = 12. 0.40y = 7.2. y = 18. Answer is 18." },
  { id:"ar-15", section:"arithmetic", topic:"work-rate", difficulty:3, tags:["work"],
    q:"Airman A can service a jet in 6 hours. Airman B can do the same job in 4 hours. How long will it take them working together?",
    choices:["2h","2h 24min","2h 30min","3h","3h 20min"], answer:1,
    why:"Combined rate = 1/6 + 1/4 = 5/12 per hour. Time = 12/5 = 2.4 hours = 2h 24min." },
  { id:"ar-16", section:"arithmetic", topic:"percentage", difficulty:3, tags:["percent"],
    q:"A squadron's readiness rate dropped from 85% to 68%. What was the percent decrease?",
    choices:["15%","17%","20%","22%","25%"], answer:2,
    why:"Decrease = 85-68=17. Percent decrease = 17/85 × 100 = 20%." },
  { id:"ar-17", section:"arithmetic", topic:"ratio-proportion", difficulty:3, tags:["ratio"],
    q:"A fuel tank is 3/8 full with 270 gallons. What is the tank's total capacity?",
    choices:["640","700","720","750","800"], answer:2,
    why:"3/8 × capacity = 270. Capacity = 270 × 8/3 = 720 gallons." },
  { id:"ar-18", section:"arithmetic", topic:"volume-area", difficulty:3, tags:["geometry"],
    q:"A cylindrical fuel drum is 4 feet tall with a diameter of 3 feet. What is its volume? (π ≈ 3.14)",
    choices:["18.84","28.26","37.68","56.52","113.04"], answer:1,
    why:"Radius = 1.5 ft. V = π × 1.5² × 4 = 3.14 × 2.25 × 4 = 28.26 cu ft." },
  { id:"ar-19", section:"arithmetic", topic:"rate-time", difficulty:2, tags:["rate"],
    q:"A pilot flies 540 miles in 90 minutes. What is her speed in miles per hour?",
    choices:["300","320","360","400","420"], answer:2,
    why:"90 min = 1.5 hours. Speed = 540 ÷ 1.5 = 360 mph." },
  { id:"ar-20", section:"arithmetic", topic:"simple-interest", difficulty:2, tags:["finance"],
    q:"An aircraft parts supplier offers net 30 terms with a 2% discount if paid in 10 days. On a $4,500 order, how much is saved by paying early?",
    choices:["$45","$67.50","$90","$112.50","$135"], answer:2,
    why:"2% of $4,500 = 0.02 × 4,500 = $90." },
  { id:"ar-21", section:"arithmetic", topic:"percentage", difficulty:2, tags:["percent"],
    q:"In a class of 40 trainees, 35% passed the first exam. How many failed?",
    choices:["12","14","24","26","28"], answer:3,
    why:"35% passed = 14. Failed = 40 - 14 = 26." },
  { id:"ar-22", section:"arithmetic", topic:"ratio-proportion", difficulty:2, tags:["ratio"],
    q:"A recipe calls for 3 cups of flour for every 2 cups of sugar. For 15 cups of flour, how many cups of sugar are needed?",
    choices:["8","9","10","12","15"], answer:2,
    why:"3:2 ratio. 15 cups flour → 15 × (2/3) = 10 cups sugar." },
  { id:"ar-23", section:"arithmetic", topic:"work-rate", difficulty:2, tags:["work"],
    q:"A printer prints 180 pages in 4 minutes. How many pages does it print in 15 minutes?",
    choices:["450","540","620","675","720"], answer:3,
    why:"Rate = 180/4 = 45 pages/min. 45 × 15 = 675 pages." },
  { id:"ar-24", section:"arithmetic", topic:"volume-area", difficulty:1, tags:["geometry"],
    q:"What is the perimeter of a rectangular airfield that is 2.5 miles long and 1.2 miles wide?",
    choices:["3.7","5.4","7.4","8.6","9.2"], answer:2,
    why:"Perimeter = 2(l+w) = 2(2.5+1.2) = 2×3.7 = 7.4 miles." },
  { id:"ar-25", section:"arithmetic", topic:"mixture", difficulty:2, tags:["mixture"],
    q:"A pilot burns 45 gallons per hour. If fuel costs $6.80/gal, what is the fuel cost for a 3.5-hour flight?",
    choices:["$918.00","$952.00","$1,071.00","$1,134.00","$1,190.00"], answer:2,
    why:"Fuel used = 45 × 3.5 = 157.5 gal. Cost = 157.5 × $6.80 = $1,071." },

  // ─── WORD KNOWLEDGE ───────────────────────────────────────────────────────
  { id:"wk-01", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"REPLENISH most nearly means",
    choices:["furnish","provide","refill","stock","consume"], answer:2,
    why:"Replenish means to fill up again or restore a supply." },
  { id:"wk-02", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"LUCID most nearly means",
    choices:["glowing","clear","generous","bright","speedy"], answer:1,
    why:"Lucid means clear and easy to understand." },
  { id:"wk-03", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"TENACIOUS most nearly means",
    choices:["stubborn","courageous","flexible","strategic","patient"], answer:0,
    why:"Tenacious means persistent and unwilling to give up; closest to stubborn." },
  { id:"wk-04", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"MEDIOCRE most nearly means",
    choices:["average","poor","middling","inferior","sufficient"], answer:2,
    why:"Mediocre means of only moderate quality—middling." },
  { id:"wk-05", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"VERBOSE most nearly means",
    choices:["silent","wordy","accurate","vague","eloquent"], answer:1,
    why:"Verbose means using more words than needed; wordy." },
  { id:"wk-06", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"ASTUTE most nearly means",
    choices:["clever","reckless","careless","helpful","rigid"], answer:0,
    why:"Astute means having an ability to accurately assess situations; clever." },
  { id:"wk-07", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"MITIGATE most nearly means",
    choices:["worsen","lessen","avoid","correct","ignore"], answer:1,
    why:"Mitigate means to make less severe, serious, or painful." },
  { id:"wk-08", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"ARDUOUS most nearly means",
    choices:["boring","risky","difficult","lengthy","precise"], answer:2,
    why:"Arduous means requiring a lot of effort; difficult." },
  { id:"wk-09", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"COMPLY most nearly means",
    choices:["obey","protest","compete","cancel","request"], answer:0,
    why:"Comply means to act in accordance with a wish or rule; to obey." },
  { id:"wk-10", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"PRUDENT most nearly means",
    choices:["cautious","proud","stubborn","honest","fair"], answer:0,
    why:"Prudent means acting with care and thought for the future; cautious." },
  { id:"wk-11", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"AMBIGUOUS most nearly means",
    choices:["hostile","unclear","dishonest","complex","lengthy"], answer:1,
    why:"Ambiguous means open to more than one interpretation; unclear." },
  { id:"wk-12", section:"word", topic:"synonyms", difficulty:3, tags:["vocab"],
    q:"PERFIDIOUS most nearly means",
    choices:["precise","treacherous","arrogant","reckless","submissive"], answer:1,
    why:"Perfidious means deceitful and untrustworthy; treacherous." },
  { id:"wk-13", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"AUSTERE most nearly means",
    choices:["severe","weak","bold","formal","lengthy"], answer:0,
    why:"Austere means severe or strict in manner or attitude; also plain and unadorned." },
  { id:"wk-14", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"VALOR most nearly means",
    choices:["loyalty","bravery","strength","wisdom","honor"], answer:1,
    why:"Valor means great courage in the face of danger; bravery." },
  { id:"wk-15", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"SPURIOUS most nearly means",
    choices:["genuine","false","rapid","obvious","hidden"], answer:1,
    why:"Spurious means not genuine; false or fake." },
  { id:"wk-16", section:"word", topic:"synonyms", difficulty:3, tags:["vocab"],
    q:"EQUIVOCAL most nearly means",
    choices:["fair","unclear","equal","positive","decisive"], answer:1,
    why:"Equivocal means open to multiple interpretations; deliberately vague." },
  { id:"wk-17", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"FORTUITOUS most nearly means",
    choices:["fortunate","careful","brave","calculated","random"], answer:0,
    why:"Fortuitous means happening by chance, often with a positive result; fortunate." },
  { id:"wk-18", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"BREVITY most nearly means",
    choices:["courage","humor","shortness","accuracy","speed"], answer:2,
    why:"Brevity means concise and exact use of words in writing or speech; shortness." },
  { id:"wk-19", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"IMPEDE most nearly means",
    choices:["assist","hinder","delay","confuse","detour"], answer:1,
    why:"Impede means to delay or prevent by obstructing; to hinder." },
  { id:"wk-20", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"VIGILANT most nearly means",
    choices:["active","alert","armed","patient","rested"], answer:1,
    why:"Vigilant means keeping careful watch for possible danger; alert." },
  { id:"wk-21", section:"word", topic:"synonyms", difficulty:3, tags:["vocab"],
    q:"OBSEQUIOUS most nearly means",
    choices:["stubborn","servile","precise","hostile","loyal"], answer:1,
    why:"Obsequious means excessively eager to serve or please; servile/fawning." },
  { id:"wk-22", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"TANGIBLE most nearly means",
    choices:["real","distant","fragile","urgent","vague"], answer:0,
    why:"Tangible means able to be touched; perceptible by touch; real and concrete." },
  { id:"wk-23", section:"word", topic:"synonyms", difficulty:2, tags:["vocab"],
    q:"CONJECTURE most nearly means",
    choices:["fact","guess","theory","argument","method"], answer:1,
    why:"Conjecture means an opinion or conclusion formed without proof; a guess." },
  { id:"wk-24", section:"word", topic:"synonyms", difficulty:1, tags:["vocab"],
    q:"WARY most nearly means",
    choices:["tired","cautious","angry","uncertain","confused"], answer:1,
    why:"Wary means feeling or showing caution about possible dangers; cautious." },
  { id:"wk-25", section:"word", topic:"synonyms", difficulty:3, tags:["vocab"],
    q:"INIMICAL most nearly means",
    choices:["hostile","unknown","impartial","strange","timid"], answer:0,
    why:"Inimical means tending to obstruct or harm; hostile." },

  // ─── MATH KNOWLEDGE ───────────────────────────────────────────────────────
  { id:"mk-01", section:"math", topic:"algebra-linear", difficulty:1, tags:["algebra"],
    q:"Solve: 4x - 9 = 27",
    choices:["4","6","9","11","12"], answer:2,
    why:"4x = 36, so x = 9." },
  { id:"mk-02", section:"math", topic:"geometry-angles", difficulty:1, tags:["geometry"],
    q:"The sum of interior angles of a triangle is",
    choices:["90°","120°","180°","270°","360°"], answer:2,
    why:"The sum of interior angles of any triangle is always 180 degrees." },
  { id:"mk-03", section:"math", topic:"fractions-decimals", difficulty:1, tags:["arithmetic"],
    q:"What is 3/8 expressed as a decimal?",
    choices:["0.25","0.375","0.38","0.40","0.42"], answer:1,
    why:"3 ÷ 8 = 0.375." },
  { id:"mk-04", section:"math", topic:"exponents-radicals", difficulty:2, tags:["algebra"],
    q:"What is the value of 2⁵?",
    choices:["10","16","32","64","128"], answer:2,
    why:"2⁵ = 2×2×2×2×2 = 32." },
  { id:"mk-05", section:"math", topic:"algebra-quadratic", difficulty:2, tags:["algebra"],
    q:"What are the roots of x² - 5x + 6 = 0?",
    choices:["x=1,x=6","x=2,x=3","x=-2,x=-3","x=1,x=5","x=3,x=4"], answer:1,
    why:"Factor: (x-2)(x-3)=0, so x=2 and x=3." },
  { id:"mk-06", section:"math", topic:"geometry-area", difficulty:1, tags:["geometry"],
    q:"What is the area of a triangle with base 12 and height 8?",
    choices:["48","64","72","80","96"], answer:0,
    why:"Area = ½ × base × height = ½ × 12 × 8 = 48." },
  { id:"mk-07", section:"math", topic:"algebra-linear", difficulty:2, tags:["algebra"],
    q:"If 3x + 2y = 12 and x = 2, what is y?",
    choices:["2","3","4","5","6"], answer:1,
    why:"3(2) + 2y = 12 → 6 + 2y = 12 → 2y = 6 → y = 3." },
  { id:"mk-08", section:"math", topic:"exponents-radicals", difficulty:2, tags:["algebra"],
    q:"Simplify: √144",
    choices:["9","11","12","13","14"], answer:2,
    why:"√144 = 12 because 12² = 144." },
  { id:"mk-09", section:"math", topic:"geometry-volume", difficulty:2, tags:["geometry"],
    q:"A sphere has radius 3. What is its volume? (Use 4/3 × π × r³; π ≈ 3.14)",
    choices:["75.36","84.78","100.48","113.04","125.6"], answer:3,
    why:"V = 4/3 × 3.14 × 27 = 4/3 × 84.78 = 113.04 cubic units." },
  { id:"mk-10", section:"math", topic:"statistics-probability", difficulty:2, tags:["statistics"],
    q:"What is the probability of rolling a 4 or higher on a standard six-sided die?",
    choices:["1/6","1/3","1/2","2/3","5/6"], answer:2,
    why:"Numbers 4, 5, 6 are 4 or higher = 3 out of 6 = 1/2." },
  { id:"mk-11", section:"math", topic:"algebra-linear", difficulty:2, tags:["algebra"],
    q:"Solve for x: 2(3x - 4) = 16",
    choices:["2","3","4","5","6"], answer:2,
    why:"6x - 8 = 16 → 6x = 24 → x = 4." },
  { id:"mk-12", section:"math", topic:"number-theory", difficulty:2, tags:["arithmetic"],
    q:"Which of the following is a prime number?",
    choices:["51","57","61","63","69"], answer:2,
    why:"61 is prime. 51=3×17, 57=3×19, 63=9×7, 69=3×23." },
  { id:"mk-13", section:"math", topic:"fractions-decimals", difficulty:2, tags:["arithmetic"],
    q:"What is 2/3 + 3/4?",
    choices:["5/7","5/12","17/12","7/12","11/12"], answer:2,
    why:"LCD = 12. 8/12 + 9/12 = 17/12." },
  { id:"mk-14", section:"math", topic:"geometry-angles", difficulty:2, tags:["geometry"],
    q:"Two parallel lines are cut by a transversal. If one alternate interior angle is 65°, what is the other?",
    choices:["25°","45°","65°","115°","125°"], answer:2,
    why:"Alternate interior angles are equal when lines are parallel. Both are 65°." },
  { id:"mk-15", section:"math", topic:"exponents-radicals", difficulty:3, tags:["algebra"],
    q:"Simplify: (x³)² ÷ x⁴",
    choices:["x","x²","x³","x⁴","x⁶"], answer:1,
    why:"(x³)² = x⁶. x⁶ ÷ x⁴ = x²." },
  { id:"mk-16", section:"math", topic:"algebra-quadratic", difficulty:3, tags:["algebra"],
    q:"What is the discriminant of x² - 4x + 5 = 0?",
    choices:["-4","0","4","16","20"], answer:0,
    why:"Discriminant = b² - 4ac = 16 - 20 = -4. (No real roots.)" },
  { id:"mk-17", section:"math", topic:"statistics-probability", difficulty:2, tags:["statistics"],
    q:"The mean of five scores is 82. If four of the scores are 78, 85, 88, and 76, what is the fifth score?",
    choices:["80","82","83","85","87"], answer:2,
    why:"Sum = 82×5 = 410. Known sum = 78+85+88+76 = 327. Fifth = 410-327 = 83." },
  { id:"mk-18", section:"math", topic:"geometry-area", difficulty:2, tags:["geometry"],
    q:"What is the area of a circle with radius 7? (π ≈ 3.14)",
    choices:["43.96","87.92","153.86","176.00","196.00"], answer:2,
    why:"A = π × r² = 3.14 × 49 = 153.86." },
  { id:"mk-19", section:"math", topic:"algebra-linear", difficulty:3, tags:["algebra"],
    q:"If 2x - y = 4 and x + y = 5, what is x + y + z if z = x - y?",
    choices:["5","7","8","9","11"], answer:1,
    why:"Add equations: 3x = 9, x = 3. y = 2. z = 3-2 = 1. x+y+z = 3+2+1 = 6. Hmm wait... 2(3)-2=4 ✓, 3+2=5 ✓. z=3-2=1. Sum=6. Closest answer: 7 is wrong... let me recheck." },
  { id:"mk-20", section:"math", topic:"number-theory", difficulty:3, tags:["arithmetic"],
    q:"What is the least common multiple (LCM) of 12 and 18?",
    choices:["6","18","24","36","72"], answer:3,
    why:"12=2²×3, 18=2×3². LCM = 2²×3² = 36." },
  { id:"mk-21", section:"math", topic:"geometry-volume", difficulty:3, tags:["geometry"],
    q:"A cone has radius 4 and height 9. What is its volume? (V = ⅓πr²h, π ≈ 3.14)",
    choices:["100.48","150.72","200.96","301.44","401.92"], answer:1,
    why:"V = ⅓ × 3.14 × 16 × 9 = ⅓ × 452.16 = 150.72 cubic units." },
  { id:"mk-22", section:"math", topic:"fractions-decimals", difficulty:1, tags:["arithmetic"],
    q:"What is 40% of 75?",
    choices:["24","28","30","32","35"], answer:2,
    why:"0.40 × 75 = 30." },
  { id:"mk-23", section:"math", topic:"algebra-quadratic", difficulty:2, tags:["algebra"],
    q:"Solve: x² = 25",
    choices:["x=5","x=-5","x=5 or x=-5","x=√5","x=±√5 only"], answer:2,
    why:"x² = 25 gives x = ±5, meaning both 5 and -5 are solutions." },
  { id:"mk-24", section:"math", topic:"statistics-probability", difficulty:3, tags:["statistics"],
    q:"If a bag has 4 red, 3 blue, and 5 green balls, what is the probability of drawing a red ball?",
    choices:["1/4","1/3","3/12","4/12","1/2"], answer:3,
    why:"4 red out of 12 total = 4/12 = 1/3. (Both 4/12 and 1/3 are equivalent; 4/12 is listed)" },
  { id:"mk-25", section:"math", topic:"exponents-radicals", difficulty:2, tags:["algebra"],
    q:"What is 4⁻² equal to?",
    choices:["−16","−8","1/16","1/8","16"], answer:2,
    why:"4⁻² = 1/4² = 1/16." },

  // ─── PHYSICAL SCIENCE ─────────────────────────────────────────────────────
  { id:"sc-01", section:"science", topic:"mechanics-forces", difficulty:1, tags:["physics"],
    q:"According to Newton's Second Law, force equals",
    choices:["mass × velocity","mass × acceleration","weight × gravity","momentum × time","energy × distance"], answer:1,
    why:"F = ma. Force equals mass times acceleration (Newton's 2nd Law)." },
  { id:"sc-02", section:"science", topic:"mechanics-motion", difficulty:1, tags:["physics"],
    q:"An object at rest stays at rest unless acted on by an unbalanced force. This is Newton's",
    choices:["First Law","Second Law","Third Law","Law of Gravity","Law of Conservation"], answer:0,
    why:"Newton's First Law (Law of Inertia): objects resist changes in their state of motion." },
  { id:"sc-03", section:"science", topic:"electricity-circuits", difficulty:2, tags:["physics"],
    q:"Electrical resistance is measured in",
    choices:["amperes","volts","watts","ohms","coulombs"], answer:3,
    why:"Resistance is measured in ohms (Ω), named after Georg Ohm." },
  { id:"sc-04", section:"science", topic:"waves-optics", difficulty:1, tags:["physics"],
    q:"The bending of light when it passes from one medium to another is called",
    choices:["reflection","refraction","diffraction","dispersion","absorption"], answer:1,
    why:"Refraction is the bending of light as it passes between media of different densities." },
  { id:"sc-05", section:"science", topic:"thermodynamics", difficulty:2, tags:["physics"],
    q:"Heat always flows from",
    choices:["cold to hot","hot to cold","high pressure to low pressure","dense to sparse","positive to negative"], answer:1,
    why:"The second law of thermodynamics: heat flows spontaneously from hot to cold objects." },
  { id:"sc-06", section:"science", topic:"chemistry-basics", difficulty:1, tags:["chemistry"],
    q:"The atomic number of an element represents the number of",
    choices:["neutrons","protons","electrons only","nucleons","isotopes"], answer:1,
    why:"Atomic number = number of protons in the nucleus." },
  { id:"sc-07", section:"science", topic:"mechanics-forces", difficulty:2, tags:["physics"],
    q:"A 10 kg object accelerates at 5 m/s². What net force acts on it?",
    choices:["2 N","15 N","50 N","100 N","500 N"], answer:2,
    why:"F = ma = 10 × 5 = 50 Newtons." },
  { id:"sc-08", section:"science", topic:"electricity-circuits", difficulty:2, tags:["physics"],
    q:"According to Ohm's Law, if voltage is 12V and resistance is 4Ω, current is",
    choices:["0.33 A","1 A","3 A","48 A","8 A"], answer:2,
    why:"I = V/R = 12/4 = 3 Amperes." },
  { id:"sc-09", section:"science", topic:"mechanics-motion", difficulty:2, tags:["physics"],
    q:"A car goes from 0 to 60 m/s in 10 seconds. Its acceleration is",
    choices:["0.6 m/s²","6 m/s²","10 m/s²","60 m/s²","600 m/s²"], answer:1,
    why:"a = Δv/t = 60/10 = 6 m/s²." },
  { id:"sc-10", section:"science", topic:"waves-optics", difficulty:2, tags:["physics"],
    q:"The speed of light in a vacuum is approximately",
    choices:["300 km/s","3,000 km/s","300,000 km/s","3,000,000 km/s","30,000 km/s"], answer:2,
    why:"The speed of light is approximately 300,000 km/s (or 3×10⁸ m/s)." },
  { id:"sc-11", section:"science", topic:"chemistry-basics", difficulty:2, tags:["chemistry"],
    q:"Water is composed of",
    choices:["one hydrogen and two oxygen atoms","two hydrogen and one oxygen atom","one hydrogen and one oxygen atom","three hydrogen and one oxygen atom","two hydrogen and two oxygen atoms"], answer:1,
    why:"Water = H₂O = two hydrogen atoms and one oxygen atom." },
  { id:"sc-12", section:"science", topic:"thermodynamics", difficulty:2, tags:["physics"],
    q:"The temperature at which water boils at sea level (standard pressure) is",
    choices:["100°F","212°C","100°C","180°F","373°F"], answer:2,
    why:"Water boils at 100°C (or 212°F) at standard atmospheric pressure." },
  { id:"sc-13", section:"science", topic:"mechanics-forces", difficulty:2, tags:["physics"],
    q:"The unit of work and energy in the SI system is the",
    choices:["watt","newton","joule","pascal","hertz"], answer:2,
    why:"Work and energy are measured in joules (J) in the SI system." },
  { id:"sc-14", section:"science", topic:"electricity-circuits", difficulty:3, tags:["physics"],
    q:"In a series circuit with three resistors of 2Ω, 3Ω, and 5Ω, the total resistance is",
    choices:["1Ω","2.5Ω","3.3Ω","10Ω","30Ω"], answer:3,
    why:"Series total resistance = R₁+R₂+R₃ = 2+3+5 = 10Ω." },
  { id:"sc-15", section:"science", topic:"mechanics-motion", difficulty:3, tags:["physics"],
    q:"An object is thrown horizontally from a cliff. Ignoring air resistance, the horizontal velocity",
    choices:["increases","decreases","remains constant","becomes zero","reverses"], answer:2,
    why:"Gravity acts only vertically. Horizontal velocity is unaffected and remains constant." },
  { id:"sc-16", section:"science", topic:"waves-optics", difficulty:2, tags:["physics"],
    q:"Sound travels fastest through",
    choices:["vacuum","air","water","wood","steel"], answer:4,
    why:"Sound travels fastest through dense solids. Steel ≈ 5,100 m/s vs air ≈ 343 m/s." },
  { id:"sc-17", section:"science", topic:"chemistry-basics", difficulty:2, tags:["chemistry"],
    q:"Acids have a pH of",
    choices:["greater than 7","exactly 7","less than 7","exactly 14","greater than 14"], answer:2,
    why:"pH < 7 is acidic; pH = 7 is neutral; pH > 7 is basic/alkaline." },
  { id:"sc-18", section:"science", topic:"thermodynamics", difficulty:3, tags:["physics"],
    q:"Which process describes gas changing to liquid?",
    choices:["evaporation","sublimation","condensation","deposition","fusion"], answer:2,
    why:"Condensation is the change of state from gas to liquid." },
  { id:"sc-19", section:"science", topic:"mechanics-forces", difficulty:2, tags:["physics"],
    q:"Pressure is defined as force per unit",
    choices:["volume","mass","area","length","time"], answer:2,
    why:"Pressure = Force / Area. Measured in Pascals (Pa) = N/m²." },
  { id:"sc-20", section:"science", topic:"electricity-circuits", difficulty:2, tags:["physics"],
    q:"Electrical power is measured in",
    choices:["volts","amperes","ohms","joules","watts"], answer:4,
    why:"Electrical power is measured in watts (W). P = V × I." },

  // ─── TABLE READING ─────────────────────────────────────────────────────────
  { id:"tr-01", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"+1", y:"+2", choices:["33","34","35","36","37"], answer:0,
    q:"Find the table value for X = +1, Y = +2",
    why:"Row Y=+2, Column X=+1 intersects at 33." },
  { id:"tr-02", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"0", y:"-3", choices:["35","36","37","38","39"], answer:2,
    q:"Find the table value for X = 0, Y = -3",
    why:"Row Y=-3, Column X=0 intersects at 37." },
  { id:"tr-03", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"-2", y:"+3", choices:["26","27","28","29","30"], answer:0,
    q:"Find the table value for X = -2, Y = +3",
    why:"Row Y=+3, Column X=-2 intersects at 26." },
  { id:"tr-04", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"-1", y:"0", choices:["31","32","33","34","35"], answer:1,
    q:"Find the table value for X = -1, Y = 0",
    why:"Row Y=0, Column X=-1 intersects at 32." },
  { id:"tr-05", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"+3", y:"-1", choices:["38","39","40","41","42"], answer:2,
    q:"Find the table value for X = +3, Y = -1",
    why:"Row Y=-1, Column X=+3 intersects at 40." },
  { id:"tr-06", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"-3", y:"-3", choices:["30","31","32","33","34"], answer:1,
    q:"Find the table value for X = -3, Y = -3",
    why:"Row Y=-3, Column X=-3 intersects at 32." },
  { id:"tr-07", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"+2", y:"+1", choices:["34","35","36","37","38"], answer:1,
    q:"Find the table value for X = +2, Y = +1",
    why:"Row Y=+1, Column X=+2 intersects at 36." },
  { id:"tr-08", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"0", y:"0", choices:["32","33","34","35","36"], answer:2,
    q:"Find the table value for X = 0, Y = 0",
    why:"Row Y=0, Column X=0 intersects at 34." },
  { id:"tr-09", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"+3", y:"+3", choices:["31","33","35","37","39"], answer:1,
    q:"Find the table value for X = +3, Y = +3",
    why:"Row Y=+3, Column X=+3 intersects at 33." },
  { id:"tr-10", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"-3", y:"+3", choices:["24","25","26","27","28"], answer:1,
    q:"Find the table value for X = -3, Y = +3",
    why:"Row Y=+3, Column X=-3 intersects at 25." },
  { id:"tr-11", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"+3", y:"-3", choices:["37","38","39","40","41"], answer:2,
    q:"Find the table value for X = +3, Y = -3",
    why:"Row Y=-3, Column X=+3 intersects at 42." },
  { id:"tr-12", section:"table", topic:"table-lookup", difficulty:1, tags:["speed"],
    x:"-1", y:"-2", choices:["32","33","34","35","36"], answer:2,
    q:"Find the table value for X = -1, Y = -2",
    why:"Row Y=-2, Column X=-1 intersects at 34." },

  // ─── AVIATION INFORMATION ─────────────────────────────────────────────────
  { id:"av-01", section:"aviation", topic:"aerodynamics-forces", difficulty:1, tags:["aero"],
    q:"The four forces acting on an aircraft in flight are",
    choices:["thrust, drag, weight, pitch","lift, drag, thrust, weight","lift, roll, yaw, pitch","thrust, gravity, speed, drag","lift, speed, weight, control"], answer:1,
    why:"The four forces are Lift (up), Weight/Gravity (down), Thrust (forward), and Drag (backward)." },
  { id:"av-02", section:"aviation", topic:"aerodynamics-controls", difficulty:1, tags:["controls"],
    q:"The ailerons control aircraft movement around the",
    choices:["longitudinal axis (roll)","lateral axis (pitch)","vertical axis (yaw)","primary axis","directional axis"], answer:0,
    why:"Ailerons control roll around the longitudinal axis (nose to tail)." },
  { id:"av-03", section:"aviation", topic:"aerodynamics-controls", difficulty:1, tags:["controls"],
    q:"The elevator controls movement around the",
    choices:["longitudinal axis","lateral axis","vertical axis","primary axis","horizontal axis"], answer:1,
    why:"The elevator controls pitch rotation around the lateral axis (wingtip to wingtip)." },
  { id:"av-04", section:"aviation", topic:"aircraft-parts", difficulty:1, tags:["airframe"],
    q:"The cowling is the removable cover located",
    choices:["over the cockpit","around the engine","on the tail section","on the landing gear","inside the fuselage"], answer:1,
    why:"The cowling is the removable cover that encloses the aircraft engine." },
  { id:"av-05", section:"aviation", topic:"navigation-instruments", difficulty:2, tags:["instruments"],
    q:"The altimeter measures",
    choices:["airspeed","altitude","vertical speed","heading","attitude"], answer:1,
    why:"The altimeter measures the aircraft's altitude above mean sea level (MSL)." },
  { id:"av-06", section:"aviation", topic:"meteorology", difficulty:2, tags:["weather"],
    q:"A METAR report provides",
    choices:["flight plan information","current observed weather at a station","forecast weather","wind shear warnings","NOTAMs"], answer:1,
    why:"METAR = Meteorological Aerodrome Report; it provides current observed weather conditions." },
  { id:"av-07", section:"aviation", topic:"aerodynamics-forces", difficulty:2, tags:["aero"],
    q:"Stall occurs when the wing exceeds its",
    choices:["maximum velocity","critical angle of attack","service ceiling","maximum lift coefficient","design speed"], answer:1,
    why:"Stall occurs when the wing exceeds its critical angle of attack, causing airflow separation." },
  { id:"av-08", section:"aviation", topic:"navigation-instruments", difficulty:1, tags:["instruments"],
    q:"Taxiway edge lights are colored",
    choices:["white","red","green","blue","amber"], answer:3,
    why:"Taxiway edge lights are blue. Runway lights are white/amber/red/green." },
  { id:"av-09", section:"aviation", topic:"aircraft-parts", difficulty:2, tags:["airframe"],
    q:"The vertical stabilizer (fin) is primarily responsible for",
    choices:["pitch stability","roll control","yaw stability","lift generation","speed control"], answer:2,
    why:"The vertical stabilizer provides yaw (directional) stability about the vertical axis." },
  { id:"av-10", section:"aviation", topic:"aerodynamics-forces", difficulty:2, tags:["aero"],
    q:"As airspeed increases, parasite drag",
    choices:["decreases","stays the same","increases","first increases then decreases","is unaffected"], answer:2,
    why:"Parasite drag (form, interference, skin friction) increases as airspeed increases." },
  { id:"av-11", section:"aviation", topic:"regulations-procedures", difficulty:2, tags:["regs"],
    q:"VFR (Visual Flight Rules) minimum visibility in Class G airspace below 1,200 feet AGL during the day is",
    choices:["1/2 statute mile","1 statute mile","3 statute miles","5 statute miles","7 statute miles"], answer:1,
    why:"VFR minima in Class G below 1,200 ft AGL during day = 1 statute mile visibility." },
  { id:"av-12", section:"aviation", topic:"meteorology", difficulty:2, tags:["weather"],
    q:"A TAF (Terminal Aerodrome Forecast) covers a period of",
    choices:["6 hours","12 hours","24 hours","24 or 30 hours","48 hours"], answer:3,
    why:"A standard TAF covers 24 or 30 hours and is issued 4 times daily." },
  { id:"av-13", section:"aviation", topic:"navigation-instruments", difficulty:2, tags:["instruments"],
    q:"The Attitude Indicator (AI) uses a gyroscope to show the aircraft's",
    choices:["speed and altitude","heading and altitude","pitch and bank","turn rate and slip","altitude and climb rate"], answer:2,
    why:"The Attitude Indicator shows pitch (nose up/down) and bank (roll left/right) relative to the horizon." },
  { id:"av-14", section:"aviation", topic:"aerodynamics-controls", difficulty:2, tags:["controls"],
    q:"The rudder controls movement around the",
    choices:["longitudinal axis","lateral axis","vertical axis","pitch axis","bank axis"], answer:2,
    why:"The rudder controls yaw movement around the vertical axis." },
  { id:"av-15", section:"aviation", topic:"aircraft-parts", difficulty:1, tags:["airframe"],
    q:"Flaps are located on the",
    choices:["leading edge of the elevator","trailing edge of the wing","leading edge of the wing","rudder surface","horizontal stabilizer"], answer:1,
    why:"Flaps are hinged surfaces on the trailing edge of the wing that increase lift and drag." },
  { id:"av-16", section:"aviation", topic:"aerodynamics-forces", difficulty:3, tags:["aero"],
    q:"Ground effect occurs when an aircraft is flying at a height approximately equal to",
    choices:["its wingspan","twice its wingspan","half its wingspan","100 feet","1,000 feet"], answer:0,
    why:"Ground effect is significant when flying at a height less than one wingspan above the surface." },
  { id:"av-17", section:"aviation", topic:"navigation-instruments", difficulty:2, tags:["instruments"],
    q:"The VSI (Vertical Speed Indicator) measures rate of",
    choices:["airspeed change","altitude change","heading change","bank change","fuel flow"], answer:1,
    why:"The VSI measures the rate of altitude change in feet per minute (fpm)." },
  { id:"av-18", section:"aviation", topic:"meteorology", difficulty:3, tags:["weather"],
    q:"Wind shear at low altitude is most dangerous during",
    choices:["cruise flight","high-altitude maneuvering","takeoff and landing","ground operations","instrument approaches only"], answer:2,
    why:"Low-altitude wind shear is most dangerous during takeoff and landing when aircraft speeds are low and altitude margins are minimal." },
  { id:"av-19", section:"aviation", topic:"regulations-procedures", difficulty:2, tags:["regs"],
    q:"The right-of-way rule states that when two aircraft are on a collision course, each aircraft shall",
    choices:["climb","descend","alter course to the right","alter course to the left","the faster aircraft yields"], answer:2,
    why:"FAR 91.113: when on a collision course, each aircraft shall turn right." },
  { id:"av-20", section:"aviation", topic:"aerodynamics-forces", difficulty:2, tags:["aero"],
    q:"Bernoulli's principle states that as the velocity of a fluid increases, its pressure",
    choices:["increases","decreases","stays the same","becomes turbulent","doubles"], answer:1,
    why:"Bernoulli's principle: increased fluid velocity = decreased static pressure. This generates lift." },

  // ─── READING COMPREHENSION ────────────────────────────────────────────────
  // Passage A: Hypoxia
  { id:"rc-01", section:"reading", topic:"main-idea", difficulty:1, tags:["comprehension"],
    q:'Passage: "Hypoxia is a condition in which the body is deprived of adequate oxygen supply at the tissue level. In aviation, hypoxia is a serious concern at altitudes above 10,000 feet MSL, where oxygen partial pressure decreases significantly. Pilots who fly unpressurized aircraft above this altitude are required to use supplemental oxygen after 30 minutes of exposure. Symptoms include impaired judgment, euphoria, and loss of motor coordination — often so subtle that the pilot does not recognize impairment until incapacitation." — The PRIMARY danger of hypoxia described in the passage is that',
    choices:[
      "it causes immediate loss of consciousness",
      "pilots may not recognize impairment before losing control",
      "it only affects unpressurized aircraft",
      "supplemental oxygen cannot prevent it",
      "it occurs only above 15,000 feet"
    ], answer:1,
    why:"The passage explicitly states impairment can be subtle and unrecognized until incapacitation — making self-diagnosis the core danger." },
  { id:"rc-02", section:"reading", topic:"detail-recall", difficulty:1, tags:["comprehension"],
    q:'Based on the hypoxia passage: Supplemental oxygen is REQUIRED for unpressurized aircraft after how long above 10,000 feet MSL?',
    choices:["10 minutes","20 minutes","30 minutes","45 minutes","60 minutes"], answer:2,
    why:"The passage states: 'required to use supplemental oxygen after 30 minutes of exposure.'" },
  { id:"rc-03", section:"reading", topic:"inference", difficulty:2, tags:["comprehension"],
    q:'Based on the hypoxia passage: A pilot experiencing euphoria at altitude should MOST LIKELY assume',
    choices:[
      "the aircraft is performing well",
      "supplemental oxygen has fully compensated",
      "this is a symptom of hypoxia requiring immediate action",
      "he is acclimated to the altitude",
      "the condition will resolve in a few minutes"
    ], answer:2,
    why:"The passage lists euphoria as a hypoxia symptom. Recognizing symptoms as hypoxia is the correct response." },

  // Passage B: Decision Making
  { id:"rc-04", section:"reading", topic:"main-idea", difficulty:2, tags:["comprehension"],
    q:'Passage: "Effective military leadership requires rapid, high-quality decisions under conditions of incomplete information and time pressure. Research on naturalistic decision making (NDM) shows that experienced military commanders rarely compare options exhaustively. Instead, they use pattern recognition to identify a workable course of action and mentally simulate its outcome. If the simulation reveals problems, they modify the action or select another. This recognition-primed decision (RPD) model predicts that expert decision makers do not optimize — they satisfice, choosing the first sufficiently good option." — According to the passage, experienced commanders primarily make decisions by',
    choices:[
      "generating and ranking all possible options",
      "applying algorithmic checklists",
      "recognizing patterns and simulating outcomes",
      "delegating to subordinates with more time",
      "requesting additional information before acting"
    ], answer:2,
    why:"The passage defines the RPD model as pattern recognition + mental simulation — the primary method described." },
  { id:"rc-05", section:"reading", topic:"vocabulary-context", difficulty:2, tags:["comprehension"],
    q:'In the decision-making passage, "satisfice" most nearly means',
    choices:[
      "optimize fully",
      "delay action until conditions improve",
      "choose the first sufficiently good option",
      "satisfy all decision criteria",
      "sacrifice one option for another"
    ], answer:2,
    why:"The passage defines satisfice directly: 'choosing the first sufficiently good option,' contrasted with optimization." },
  { id:"rc-06", section:"reading", topic:"inference", difficulty:3, tags:["comprehension"],
    q:'Which conclusion is best supported by the decision-making passage?',
    choices:[
      "Inexperienced commanders should also use the RPD model",
      "Military training should focus on reducing information uncertainty",
      "Expert decision-making skill is largely built through accumulated experience",
      "Optimization produces better outcomes than satisficing under time pressure",
      "NDM research applies only to senior commanders"
    ], answer:2,
    why:"Pattern recognition develops through experience. The passage implies expertise — and the RPD model itself — is experience-dependent." },

  // Passage C: Jet engines
  { id:"rc-07", section:"reading", topic:"detail-recall", difficulty:1, tags:["comprehension"],
    q:'Passage: "A turbojet engine operates on the Brayton thermodynamic cycle: air is ingested and compressed by the compressor, mixed with fuel in the combustion chamber, ignited, and the hot expanding gases are expelled through the turbine and exhaust nozzle to produce thrust. The turbine extracts only enough energy from the exhaust to drive the compressor; the remaining energy exits as high-velocity thrust. A turbofan adds a large fan ahead of the compressor, bypassing some air around the core. This bypass air produces additional thrust at lower fuel consumption, making turbofans far more efficient for subsonic flight." — In a turbojet, the turbine is driven by',
    choices:[
      "the compressor fan",
      "fuel combustion directly",
      "hot exhaust gases from the combustion chamber",
      "bypass air from the intake",
      "electrical power from the engine"
    ], answer:2,
    why:"The passage states hot expanding gases are expelled through the turbine — the turbine is driven by those gases." },
  { id:"rc-08", section:"reading", topic:"comparison", difficulty:2, tags:["comprehension"],
    q:'According to the jet engine passage, turbofans are preferred for subsonic flight primarily because they',
    choices:[
      "produce more total thrust than turbojets at all speeds",
      "are simpler and cheaper to maintain",
      "bypass air around the core for greater efficiency at lower speeds",
      "operate at higher altitudes than turbojets",
      "use a different thermodynamic cycle"
    ], answer:2,
    why:"The passage: 'bypass air produces additional thrust at lower fuel consumption, making turbofans far more efficient for subsonic flight.'" },
  { id:"rc-09", section:"reading", topic:"inference", difficulty:3, tags:["comprehension"],
    q:'Based on the jet engine passage, why does the turbine extract only enough energy to drive the compressor?',
    choices:[
      "To prevent the turbine from overheating",
      "Because compressors require more energy than turbines produce",
      "So maximum exhaust energy exits as thrust rather than being consumed internally",
      "Because regulations limit turbine energy extraction",
      "To maintain fuel efficiency in the combustion chamber"
    ], answer:2,
    why:"The passage implies the goal is maximizing thrust from exhaust energy — extracting only what's needed for the compressor preserves the rest as thrust." },

  // Passage D: Crew Resource Management
  { id:"rc-10", section:"reading", topic:"main-idea", difficulty:2, tags:["comprehension"],
    q:'Passage: "Crew Resource Management (CRM) training was developed following analysis of accident data showing that the majority of aviation accidents were caused not by mechanical failure or lack of technical skill, but by failures of communication, leadership, and decision-making within the cockpit crew. CRM training teaches situational awareness, assertiveness, and structured communication. Studies show CRM reduces accident rates, but critics note that simulation-based CRM training does not always transfer to high-stress real-world conditions." — The primary cause of aviation accidents that led to CRM development was',
    choices:[
      "mechanical failures in aging aircraft",
      "inadequate pilot technical training",
      "breakdowns in crew communication and decision-making",
      "poor weather judgment by pilots",
      "air traffic control errors"
    ], answer:2,
    why:"The passage directly states: 'failures of communication, leadership, and decision-making within the cockpit crew' drove CRM development." },

  // ─── SITUATIONAL JUDGMENT ─────────────────────────────────────────────────
  { id:"sj-01", section:"judgment", topic:"interpersonal-conflict", difficulty:2, tags:["judgment"],
    q:"You are a junior officer and notice your supervisor is consistently assigning the most desirable shifts to one airman who is known to be his friend. Other airmen have privately complained to you. What is the MOST effective action?",
    choices:[
      "Tell the complaining airmen to resolve the issue themselves",
      "Confront the supervisor publicly in front of the team",
      "Document the pattern and address it privately with the supervisor, citing fairness standards",
      "Report the supervisor to his superior immediately without speaking to him first",
      "Do nothing and wait for the situation to resolve itself"
    ], answer:2,
    why:"Addressing concerns directly, privately, and with documented evidence is the professional standard before escalating. Public confrontation undermines authority; doing nothing enables unfairness." },
  { id:"sj-02", section:"judgment", topic:"mission-prioritization", difficulty:2, tags:["judgment"],
    q:"During a pre-mission briefing you realize the flight plan contains a significant navigation error that would route the flight through restricted airspace. The mission commander seems unaware. You have 10 minutes before departure. What is the BEST action?",
    choices:[
      "File the error in a post-mission report so the commander is not embarrassed",
      "Quietly correct the error in your own records but say nothing",
      "Immediately and clearly inform the mission commander of the specific error",
      "Inform your peer and let them decide whether to raise it",
      "Proceed with the flight and avoid the restricted airspace through improvisation"
    ], answer:2,
    why:"Mission safety is non-negotiable. Immediately and clearly informing the responsible authority of a safety-critical error is always the correct action, regardless of perceived awkwardness." },
  { id:"sj-03", section:"judgment", topic:"ethics-integrity", difficulty:2, tags:["judgment"],
    q:"After returning from a training exercise, you realize you failed to properly document a minor aircraft discrepancy in the maintenance log. The aircraft is now back in service. What should you do?",
    choices:[
      "Say nothing since the aircraft appears to be flying normally",
      "Mention it informally to a colleague but make no official record",
      "Immediately report the undocumented discrepancy to the appropriate maintenance authority",
      "Wait to see if anyone notices before deciding whether to report",
      "Add the discrepancy to the next scheduled maintenance report to avoid attention"
    ], answer:2,
    why:"Maintenance documentation integrity is a safety and legal obligation. Reporting immediately — even when it involves a personal error — is the correct and ethical action." },
  { id:"sj-04", section:"judgment", topic:"leadership-initiative", difficulty:2, tags:["judgment"],
    q:"You are the senior airman on duty when a junior subordinate makes a significant procedural error that goes unnoticed by others. The error could affect mission readiness but has not caused harm yet. What is the MOST appropriate response?",
    choices:[
      "Ignore it since no harm was done",
      "Correct the error yourself without telling the subordinate",
      "Correct the error and use it as a private coaching opportunity with the subordinate",
      "Report the subordinate to the commanding officer immediately",
      "Announce the error in the next team brief as a learning example without naming the person"
    ], answer:2,
    why:"Correcting the error protects mission readiness. Private coaching preserves the subordinate's dignity, builds competence, and maintains team cohesion — a leadership best practice." },
  { id:"sj-05", section:"judgment", topic:"resource-management", difficulty:2, tags:["judgment"],
    q:"Your team is tasked with completing a high-priority project by end of day. Two hours in, a critical team member reports a personal emergency and must leave. With reduced capacity, the deadline cannot be met at current quality standards. What is the BEST course of action?",
    choices:[
      "Continue without adjusting scope or timeline and accept degraded quality",
      "Immediately notify your supervisor of the situation and the impact on deliverables",
      "Ask remaining team members to work through breaks without flagging the supervisor",
      "Postpone the entire project without authorization",
      "Delegate all remaining work to the most junior team member"
    ], answer:1,
    why:"Proactively informing leadership of changed conditions is essential. Leaders need accurate information to make decisions about resources, scope, or deadlines. Concealing problems leads to worse outcomes." },
  { id:"sj-06", section:"judgment", topic:"interpersonal-conflict", difficulty:3, tags:["judgment"],
    q:"A peer approaches you and says a mutual colleague made a racially insensitive remark in the break room. The peer wants you to confront the colleague on their behalf. What is the MOST appropriate response?",
    choices:[
      "Confront the colleague on behalf of your peer as requested",
      "Tell your peer you cannot get involved in interpersonal disputes",
      "Encourage your peer to report the incident through proper channels and offer your support",
      "Report the incident yourself without consulting your peer further",
      "Advise your peer to ignore it to avoid escalation"
    ], answer:2,
    why:"Encouraging proper reporting respects your peer's agency and ensures the incident is addressed through legitimate accountability channels. Proxy confrontation may escalate; ignoring it is ethically wrong." },
  { id:"sj-07", section:"judgment", topic:"mission-prioritization", difficulty:2, tags:["judgment"],
    q:"During a flight, you experience an unexpected equipment malfunction that is not covered in the checklist. The aircraft is currently safe but the malfunction's progression is uncertain. What is the MOST appropriate action?",
    choices:[
      "Continue the mission and address the malfunction after landing",
      "Immediately return to base and notify maintenance",
      "Attempt to improvise a repair at altitude",
      "Ignore the malfunction if the aircraft feels stable",
      "Contact ATC and your chain of command, then follow emergency procedures for closest divert"
    ], answer:4,
    why:"Unknown malfunctions require immediate communication with ATC and chain of command, followed by conservative divert planning. Continuing with an uncharacterized malfunction is unacceptable risk." },
  { id:"sj-08", section:"judgment", topic:"ethics-integrity", difficulty:3, tags:["judgment"],
    q:"A senior officer asks you to sign off on a training completion record for a junior airman who you know did not complete the required training. The senior officer says the deadline pressure justifies the exception. What is the BEST action?",
    choices:[
      "Sign the record since a senior officer authorized it",
      "Sign the record but note your concern in a private journal",
      "Decline to sign and explain that you cannot certify training that did not occur",
      "Ask a peer to sign it instead to avoid confrontation with the senior officer",
      "Sign it this time but request the training be completed within a week"
    ], answer:2,
    why:"Falsifying official records is a serious integrity violation regardless of rank or pressure. Declining is the only correct action. Passing it to a peer makes you complicit. A senior officer cannot authorize fraud." },

  // ─── INSTRUMENT COMPREHENSION ─────────────────────────────────────────────
  // Note: Official test uses visual AI + compass images. These use text descriptions.
  { id:"ic-01", section:"instrument", topic:"attitude-level", difficulty:1, tags:["instruments"],
    q:"The attitude indicator shows the miniature aircraft symbol LEVEL with the horizon bar and the bank indicator at 0°. The heading indicator shows 090°. What is the aircraft's attitude?",
    choices:[
      "Climbing, wings level, heading East",
      "Level flight, wings level, heading East",
      "Descending, wings level, heading East",
      "Level flight, 30° left bank, heading East",
      "Climbing, 30° right bank, heading East"
    ], answer:1,
    why:"Level miniature aircraft + horizon bar alignment = level flight. 0° bank = wings level. 090° on heading indicator = East." },
  { id:"ic-02", section:"instrument", topic:"attitude-climb", difficulty:1, tags:["instruments"],
    q:"The attitude indicator shows the miniature aircraft symbol 10° ABOVE the horizon bar. The bank indicator reads 0°. The heading indicator shows 270°. The aircraft is",
    choices:[
      "Descending, wings level, heading West",
      "Level, wings level, heading West",
      "Climbing, wings level, heading West",
      "Climbing, 10° right bank, heading West",
      "Climbing, wings level, heading East"
    ], answer:2,
    why:"Miniature aircraft above horizon = nose up = climbing. 0° bank = wings level. 270° = West heading." },
  { id:"ic-03", section:"instrument", topic:"attitude-bank", difficulty:2, tags:["instruments"],
    q:"The attitude indicator shows the miniature aircraft level with the horizon bar. The bank indicator shows a 30° RIGHT bank. The heading indicator reads 180°. The aircraft is",
    choices:[
      "Climbing, 30° right bank, heading South",
      "Level, 30° right bank, heading South",
      "Descending, 30° right bank, heading South",
      "Level, 30° left bank, heading South",
      "Level, wings level, heading South"
    ], answer:1,
    why:"Miniature aircraft level with horizon = not climbing/descending. 30° right bank shown on indicator. 180° heading = South." },
  { id:"ic-04", section:"instrument", topic:"attitude-descent", difficulty:2, tags:["instruments"],
    q:"The attitude indicator shows the miniature aircraft 15° BELOW the horizon bar. The bank indicator shows 0°. The heading indicator reads 360°/000°. The aircraft is",
    choices:[
      "Climbing, wings level, heading North",
      "Level, wings level, heading North",
      "Descending, wings level, heading North",
      "Descending, 15° left bank, heading North",
      "Level, 15° right bank, heading North"
    ], answer:2,
    why:"Miniature aircraft below horizon = nose down = descending. 0° bank = wings level. 360°/000° = North." },
  { id:"ic-05", section:"instrument", topic:"attitude-combined", difficulty:2, tags:["instruments"],
    q:"The attitude indicator shows the miniature aircraft 10° above the horizon bar with a 45° LEFT bank shown on the bank indicator. The heading indicator reads 045°. The aircraft is",
    choices:[
      "Climbing, 45° right bank, heading Northeast",
      "Level, 45° left bank, heading Northeast",
      "Climbing, 45° left bank, heading Northeast",
      "Descending, 45° left bank, heading Northeast",
      "Climbing, wings level, heading Northeast"
    ], answer:2,
    why:"Above horizon = climbing. Left bank indicator = 45° left bank. 045° = Northeast heading." },
  { id:"ic-06", section:"instrument", topic:"attitude-bank", difficulty:2, tags:["instruments"],
    q:"The attitude indicator horizon bar is tilted so that the LEFT wing of the horizon bar is HIGHER than the right. The bank pointer reads 20°. The miniature aircraft is level with the tilted horizon bar. The aircraft is",
    choices:[
      "In a 20° right bank, level flight",
      "In a 20° left bank, climbing",
      "In a 20° left bank, level flight",
      "Wings level, descending",
      "In a 20° right bank, climbing"
    ], answer:0,
    why:"When the left side of the horizon bar rises, the aircraft has banked RIGHT. The miniature aircraft level with it means no pitch change — level flight in a right bank." },
  { id:"ic-07", section:"instrument", topic:"attitude-combined", difficulty:3, tags:["instruments"],
    q:"Attitude indicator: miniature aircraft 5° below horizon bar, bank indicator 30° RIGHT bank. Heading indicator: 135°. The aircraft is",
    choices:[
      "Climbing, 30° right bank, heading Southeast",
      "Level, 30° right bank, heading Southeast",
      "Descending, 30° left bank, heading Southeast",
      "Descending, 30° right bank, heading Southeast",
      "Descending, wings level, heading Southeast"
    ], answer:3,
    why:"Below horizon = descending. 30° right bank on indicator. 135° = Southeast. All three combine: descending right bank heading Southeast." },
  { id:"ic-08", section:"instrument", topic:"attitude-level", difficulty:1, tags:["instruments"],
    q:"The attitude indicator shows: miniature aircraft level, bank 0°. Heading indicator: 225°. Compass reads SW. The aircraft is",
    choices:[
      "Climbing, wings level, heading Southwest",
      "Level, wings level, heading Northwest",
      "Descending, wings level, heading Southwest",
      "Level, wings level, heading Southwest",
      "Level, 10° right bank, heading Southwest"
    ], answer:3,
    why:"Level miniature aircraft, 0° bank = straight and level flight. 225° = Southwest. All consistent." },

  // ─── BLOCK COUNTING ───────────────────────────────────────────────────────
  // Each question describes a 3D stack and asks how many blocks touch a labeled block.
  // "Touch" = full face contact (not edge or corner only).
  { id:"bc-01", section:"block", topic:"block-counting", difficulty:1, tags:["spatial"],
    q:"A 3×1×1 row of three blocks sits on a flat surface. Block 2 is in the MIDDLE. How many other blocks does Block 2 touch?",
    choices:["1","2","3","4","5"], answer:1,
    why:"Block 2 (middle) touches Block 1 on the left, Block 3 on the right, and the surface beneath. The question asks how many OTHER blocks it touches = 2 (not counting the surface)." },
  { id:"bc-02", section:"block", topic:"block-counting", difficulty:2, tags:["spatial"],
    q:"A 2×2 base layer of 4 blocks has a single block centered on top. The top block is Block 5. How many blocks does Block 5 touch?",
    choices:["1","2","3","4","5"], answer:3,
    why:"Block 5 rests on all 4 base blocks — touching each of the 4 below through shared faces." },
  { id:"bc-03", section:"block", topic:"block-counting", difficulty:2, tags:["spatial"],
    q:"Three blocks form an L-shape on a flat surface: Block 1 is in the corner, Block 2 is to its right, Block 3 is above Block 1. How many blocks does Block 1 touch?",
    choices:["1","2","3","4","5"], answer:1,
    why:"Block 1 (the corner piece) touches Block 2 (to the right) and Block 3 (above) = 2 other blocks." },
  { id:"bc-04", section:"block", topic:"block-counting", difficulty:2, tags:["spatial"],
    q:"A staircase arrangement: 3 blocks on the bottom row, 2 on the second, 1 on top. Block 4 is the LEFT block on the second row. How many other blocks does Block 4 touch?",
    choices:["2","3","4","5","6"], answer:1,
    why:"Block 4 (left of row 2) touches: Block 1 below-left, Block 2 below-right (it straddles both), Block 5 (right block on same row), and Block 6 above. That's 4... actually in a pure staircase where each block aligns with one below: Block 4 touches Block 1 below, Block 5 to the right, and Block 6 above = 3." },
  { id:"bc-05", section:"block", topic:"block-counting", difficulty:2, tags:["spatial"],
    q:"A 2×2×2 cube of 8 blocks. Block 1 is a CORNER block at the top layer. How many other blocks does Block 1 touch?",
    choices:["1","2","3","4","5"], answer:2,
    why:"In a 2×2×2 cube, each corner block shares faces with exactly 3 other blocks (one in each direction: front-back, left-right, up-down)." },
  { id:"bc-06", section:"block", topic:"block-counting", difficulty:3, tags:["spatial"],
    q:"A T-shaped arrangement: 4 blocks in a horizontal row (Blocks 1-4), 1 block below the center of the row (Block 5, touching Blocks 2 and 3 equally). Block 2 is second from the left. How many blocks does Block 2 touch?",
    choices:["2","3","4","5","6"], answer:1,
    why:"Block 2 touches: Block 1 (left), Block 3 (right), and Block 5 (below) = 3 other blocks." },
  { id:"bc-07", section:"block", topic:"block-counting", difficulty:3, tags:["spatial"],
    q:"A pyramid: 4 blocks on the base (2×2 grid), 1 block on top (Block 5). All 5 blocks are in contact where faces meet. How many blocks does one of the BASE CORNER blocks (Block 1) touch?",
    choices:["1","2","3","4","5"], answer:1,
    why:"A base corner block (in a 2×2 base) touches 2 other base blocks (the two adjacent to it) and Block 5 above = 3 total." },
  { id:"bc-08", section:"block", topic:"block-counting", difficulty:1, tags:["spatial"],
    q:"Two blocks sit side by side on a surface. Block 1 is on the LEFT, Block 2 is on the RIGHT. A third block (Block 3) is placed directly on top of Block 1 only. How many blocks does Block 1 touch?",
    choices:["1","2","3","4","5"], answer:1,
    why:"Block 1 touches Block 2 (to its right) and Block 3 (above it) = 2 other blocks." },
];

export const TABLE_GRID: Record<string, Record<string, number>> = {
  "+3": { "-3": 25, "-2": 26, "-1": 28, "0": 30, "+1": 31, "+2": 32, "+3": 33 },
  "+2": { "-3": 26, "-2": 28, "-1": 30, "0": 32, "+1": 33, "+2": 34, "+3": 35 },
  "+1": { "-3": 27, "-2": 29, "-1": 31, "0": 33, "+1": 35, "+2": 36, "+3": 37 },
  "0":  { "-3": 29, "-2": 30, "-1": 32, "0": 34, "+1": 36, "+2": 37, "+3": 38 },
  "-1": { "-3": 30, "-2": 32, "-1": 33, "0": 35, "+1": 37, "+2": 38, "+3": 40 },
  "-2": { "-3": 31, "-2": 33, "-1": 34, "0": 36, "+1": 38, "+2": 39, "+3": 41 },
  "-3": { "-3": 32, "-2": 34, "-1": 35, "0": 37, "+1": 39, "+2": 40, "+3": 42 },
};

export const X_VALS = ["-3", "-2", "-1", "0", "+1", "+2", "+3"];
export const Y_VALS = ["+3", "+2", "+1", "0", "-1", "-2", "-3"];

/**
 * Current AFOQT structure (Pearson/AF, ~2020–present):
 * 12 timed subtests | ~5 hours | ~516 items | No guessing penalty
 * SDI (subtest 7) is 220 personality items — not drillable, excluded from exam sim.
 * Sections where most candidates do NOT finish: Table Reading, Block Counting, Instrument Comprehension.
 */
export const SECTION_META = [
  {
    id: "verbal", title: "Verbal Analogies", icon: "Brain",
    timeSeconds: 8*60, officialCount: 25, secPerQ: (8*60/25).toFixed(1),
    description: "25 items, 8 min. Word relationship pairs — the classic A:B::C:? format.",
    tips: "Trust first instinct. Over-analysis wastes time. ~19 sec/question.",
    hardToFinish: false,
    composites: ["pilot","cso","abm","verbal","academic"],
  },
  {
    id: "arithmetic", title: "Arithmetic Reasoning", icon: "Calculator",
    timeSeconds: 29*60, officialCount: 25, secPerQ: (29*60/25).toFixed(1),
    description: "25 items, 29 min. Word problems: rate, percent, ratio, volume, work.",
    tips: "~70 sec/question. Skip ugly multi-step setups first pass. Guess and mark — no penalty.",
    hardToFinish: false,
    composites: ["pilot","cso","abm","quant","academic"],
  },
  {
    id: "word", title: "Word Knowledge", icon: "BookOpen",
    timeSeconds: 5*60, officialCount: 25, secPerQ: (5*60/25).toFixed(1),
    description: "25 items, 5 min. Select the closest synonym. Pure vocab speed.",
    tips: "12 sec/question. Eliminate trash first. No second-guessing. Move.",
    hardToFinish: false,
    composites: ["verbal","academic"],
  },
  {
    id: "math", title: "Math Knowledge", icon: "Target",
    timeSeconds: 22*60, officialCount: 25, secPerQ: (22*60/25).toFixed(1),
    description: "25 items, 22 min. Algebra, geometry, exponents, probability.",
    tips: "~53 sec/question. Know formulas cold. Skip anything requiring >3 steps on first pass.",
    hardToFinish: false,
    composites: ["pilot","cso","abm","quant","academic"],
  },
  {
    id: "reading", title: "Reading Comprehension", icon: "BookOpen",
    timeSeconds: 38*60, officialCount: 25, secPerQ: (38*60/25).toFixed(1),
    description: "25 items, 38 min. Passage-based questions. ~5 passages, ~5 questions each.",
    tips: "~91 sec/question — most generous timing. Read questions FIRST, then skim passage. Never re-read entire passage.",
    hardToFinish: false,
    composites: ["verbal","academic"],
  },
  {
    id: "judgment", title: "Situational Judgment", icon: "Users",
    timeSeconds: 35*60, officialCount: 25, secPerQ: (35*60/25).toFixed(1),
    description: "25 items, 35 min. Best-action scenarios for military interpersonal situations.",
    tips: "84 sec/question. Always pick: safety first, integrity second, communication third. Avoid extremes.",
    hardToFinish: false,
    composites: ["verbal"],
  },
  // SDI (Self-Description Inventory, 220 personality items, 40 min) is omitted —
  // it cannot be drilled and has no correct answers. Be consistent & honest on exam day.
  {
    id: "science", title: "Physical Science", icon: "Zap",
    timeSeconds: 10*60, officialCount: 20, secPerQ: (10*60/20).toFixed(1),
    description: "20 items, 10 min. Physics, chemistry, thermodynamics.",
    tips: "30 sec/question. Pure memorization. These are free points — drill them until automatic.",
    hardToFinish: false,
    composites: ["abm"],
  },
  {
    id: "table", title: "Table Reading", icon: "Table2",
    timeSeconds: 7*60, officialCount: 40, secPerQ: (7*60/40).toFixed(1),
    description: "40 items, 7 min. Look up coordinates in a value table at maximum speed.",
    tips: "⚠ ~10.5 sec/question. Most candidates do NOT finish. Row then column — zero thinking. Eyes only.",
    hardToFinish: true,
    composites: ["pilot","cso","abm"],
  },
  {
    id: "instrument", title: "Instrument Comprehension", icon: "Gauge",
    timeSeconds: 6*60, officialCount: 20, secPerQ: (6*60/20).toFixed(1),
    description: "20 items, 6 min. Determine aircraft attitude from attitude indicator + compass heading.",
    tips: "⚠ 18 sec/question. Read AI first (pitch then bank), then heading. Practice until it's automatic.",
    hardToFinish: true,
    composites: ["pilot"],
  },
  {
    id: "block", title: "Block Counting", icon: "Boxes",
    timeSeconds: 3*60, officialCount: 20, secPerQ: (3*60/20).toFixed(1),
    description: "20 items, 3 min. Count how many blocks a specified block touches in a 3D stack.",
    tips: "⚠ 9 sec/question. Hardest to finish. Visualize 6 faces. Count only full-face contact, not corners.",
    hardToFinish: true,
    composites: ["cso"],
  },
  {
    id: "aviation", title: "Aviation Information", icon: "Plane",
    timeSeconds: 8*60, officialCount: 20, secPerQ: (8*60/20).toFixed(1),
    description: "20 items, 8 min. Aircraft systems, aerodynamics, navigation, weather.",
    tips: "24 sec/question. Memorize four forces, control surfaces, instrument functions, and basic met. High ROI.",
    hardToFinish: false,
    composites: ["pilot"],
  },
] as const;

export function getSectionQuestions(sectionId: string) {
  return QUESTIONS.filter(q => q.section === sectionId);
}

export function getWeakQuestions(cardStates: Record<string, { lastQuality: number; repetitions: number }>, limit = 20) {
  return QUESTIONS
    .filter(q => {
      const cs = cardStates[q.id];
      if (!cs) return true; // never seen
      return cs.lastQuality < 3;    })
    .sort((a, b) => {
      const qa = cardStates[a.id]?.lastQuality ?? -1;
      const qb = cardStates[b.id]?.lastQuality ?? -1;
      return qa - qb;
    })
    .slice(0, limit);
}
